Symphony: Problem Class Reference
Problem Class Reference abstract
Represents an abstract problem that needs to be solved.
#include <definitions.h>
Public Member Functions
Problem ()
Constructor for the Problem class.
virtual ~Problem ()
Virtual destructor for the Problem class.
virtual State * initial_state ()
Retrieves the initial state of the problem.
virtual bool goal_test (State *state)=0
Tests if a given state satisfies the goal condition.
virtual std::vector< std::shared_ptr< Action > > actions (std::shared_ptr< State > state)=0
Retrieves the set of actions applicable to a given state.
virtual double heuristic (State *state)=0
Computes a heuristic estimate for a given state.
Public Attributes
State * initial_state_
Pointer to the initial state of the problem.
Detailed Description
Represents an abstract problem that needs to be solved.
This class defines the structure of a problem, including its initial state, goal test, actions, and heuristics. It should be extended by the user to implement specific problem-solving logic.
Definition at line 63 of file definitions.h.
Constructor & Destructor Documentation
Problem()
Problem::Problem () inline
Constructor for the Problem class.
Definition at line 68 of file definitions.h.
{}
~Problem()
virtual Problem::~Problem () inline virtual
Virtual destructor for the Problem class.
Definition at line 73 of file definitions.h.
{}
Member Function Documentation
actions()
virtual std::vector< std::shared_ptr< Action > > Problem::actions (std::shared_ptr< State > state) pure virtual
Retrieves the set of actions applicable to a given state.
This method must be implemented by the user to define the available actions for a specific state.
Parameters
state The current state.
Returns
A vector of actions applicable to the given state.
Referenced by BreadthFirstSearch::search(), and AStarSearch::search().
goal_test()
virtual bool Problem::goal_test (State * state) pure virtual
Tests if a given state satisfies the goal condition.
This method must be implemented by the user to define the goal state criteria.
Parameters
state The state to test.
Returns
True if the state satisfies the goal condition, false otherwise.
Referenced by BreadthFirstSearch::search(), and AStarSearch::search().
heuristic()
virtual double Problem::heuristic (State * state) pure virtual
Computes a heuristic estimate for a given state.
This method must be implemented by the user to define a heuristic function for the problem.
Parameters
state The state for which to compute the heuristic.
Returns
A heuristic estimate of the cost to reach the goal from the given state.
Referenced by BreadthFirstSearch::search(), and AStarSearch::search().
initial_state()
virtual State * Problem::initial_state () inline virtual
Retrieves the initial state of the problem.
Returns
A pointer to the initial state.
Definition at line 80 of file definitions.h.
{ return initial_state_; }
References initial_state_.
Referenced by BreadthFirstSearch::search(), and AStarSearch::search().
Member Data Documentation
initial_state_
State* Problem::initial_state_
Pointer to the initial state of the problem.
Definition at line 113 of file definitions.h.
Referenced by initial_state().
The documentation for this class was generated from the following file:
include/definitions.h